# Generated by Django 3.2.7 on 2021-11-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('birth_data', models.DateField()),
                ('phone_data', models.CharField(max_length=13)),
            ],
        ),
    ]
